const itemData = [
	{
		"convrId": "1_8_oEQVk0mqiWtSQ0JOuPXguj5U2T4s",
		"convrType": "XDS_WECHAT_FANS_CONVERSATION",
		"name": "How  are  you、12222222222222222223131",
		"headImgUrl": "http://thirdwx.qlogo.cn/mmopen/eWfbQWITWhiaNvzXBR9OckVIyqFHnxBgSQ5wXNK0dRHeU5cGIHDZiaguib2NZqkG02Bj0sZsTMNicbrxkdiapWVv8ibsmKysIkKrbM/132",
		"createId": "0",
		"createTime": "2019-04-24 11:34:24",
		"status": 1,
		"appAccountId": 8,
		"appAccountName": "裂变营销实操",
		"appAccountheadImgUrl": "http://wx.qlogo.cn/mmopen/I4sDfBaAwcVBJ5icgaoALEGjpn25ZkIej1EjAy0rCtWZQ9oMsfwCWorDukubgNQOuN7j8TGzWXA9oXDFUQBYPwiczmiav4ibStxz/0",
		"convrOwnerSeatId": 40,
		"unreadNum": 0,
		"messageBody": {
			"className": "com.xkco.xkdata.commons.support.msg.body.event.EventBody",
			"msgId": "304",
			"name": null,
			"head": null,
			"msgType": "WX_EVENT_DELETE_ASSIS_SEAT",
			"msgTypeCode": null,
			"createTime": 1559801556563,
			"createId": "3",
			"status": null,
			"contextMap": {
				"CONVR_CLOSE_SEAT_NAME": "HappyZX002",
				"CONVR_CLOSE_SEAT_ID": 3,
				"CONVR_CLOSE_ASSIS_SEAT_NAME": "秀秀ZX004",
				"CONVR_CLOSE_ASSIS_SEAT_ID": 5
			},
			"msgBodyType": "EVENT",
			"code": "CLICK"
		},
		"convrOwnerEmployeeName": null,
		"fansFirstVisitDate": "2019-04-24 11:34:24",
		"assistSeatIds": "3",
		"fansComeToVisit": false,
		"seatContinueSpeakCount": 0,
		"fansLastVisitDate": "2019-06-05 22:06:38"
	},
	{
		"convrId": "1_12_ozdaP5s5Z_f-PjWk6osiGziqe1_o",
		"convrType": "XDS_WECHAT_FANS_CONVERSATION",
		"name": "Happy",
		"headImgUrl": "http://thirdwx.qlogo.cn/mmopen/EQDQDhn73NjzL3q3V9M9S9iaOqvNa5E9keuo9adAo33icmHOC8onicF7zUOa5vpwVWOXwgbW9WaBbo9ticFibxPSHKyGejzugricnh/132",
		"createId": "0",
		"createTime": "2019-05-10 22:24:29",
		"status": 1,
		"appAccountId": 12,
		"appAccountName": "销大师精选",
		"appAccountheadImgUrl": "http://wx.qlogo.cn/mmopen/v6XbW38nFOTibrbWbhCaaoH5IuXAVrLCpv3PTqnc0czmymnX5ZWiabQoVgW26iar1I6VZ2zxnF1tOpdJXXN2upZXSWQ0rrlY2nM/0",
		"convrOwnerSeatId": 40,
		"unreadNum": 0,
		"messageBody": {
			"className": "com.xkco.xkdata.commons.support.msg.body.text.TextBody",
			"msgId": "15",
			"name": null,
			"head": null,
			"msgType": "SEAT_WECHAT_KF_MSG",
			"msgTypeCode": null,
			"createTime": 1559715552007,
			"createId": "0",
			"status": null,
			"contextMap": {
				"nickName": "Happy"
			},
			"msgBodyType": "TEXT",
			"content": "被关注回复通过编辑内容，快速进行自动回复设置。开启后适用于以下场景：1）搜索公众号和扫公众号二维码关注，2）名片分享关注，3）图文页名称点击关\\n注，4）图文页右上角菜单关注，5）支付后关注。关闭后，粉丝通过以上方式关注公众号都无法收到被关注回复内容。\\n\\n"
		},
		"convrOwnerEmployeeName": null,
		"fansFirstVisitDate": "2019-05-10 22:24:28",
		"assistSeatIds": null,
		"fansComeToVisit": true,
		"seatContinueSpeakCount": 0,
		"fansLastVisitDate": "2019-06-05 14:19:11"
	},
	{
        "convrId": "1_8_oEQVk0mqiWtSQ0JOuPXguj5U2T4s",
        "convrType": "XDS_WECHAT_FANS_CONVERSATION",
        "name": "How  are  you、",
        "headImgUrl": "http://thirdwx.qlogo.cn/mmopen/eWfbQWITWhiaNvzXBR9OckVIyqFHnxBgSQ5wXNK0dRHeU5cGIHDZiaguib2NZqkG02Bj0sZsTMNicbrxkdiapWVv8ibsmKysIkKrbM/132",
        "createId": "0",
        "createTime": "2019-04-24 11:34:24",
        "status": 1,
        "appAccountId": 8,
        "appAccountName": "裂变营销实操",
        "appAccountheadImgUrl": "http://wx.qlogo.cn/mmopen/I4sDfBaAwcVBJ5icgaoALEGjpn25ZkIej1EjAy0rCtWZQ9oMsfwCWorDukubgNQOuN7j8TGzWXA9oXDFUQBYPwiczmiav4ibStxz/0",
        "convrOwnerSeatId": 40,
        "unreadNum": 0,
        "messageBody": {
          "className": "com.xkco.xkdata.commons.support.msg.body.event.EventBody",
          "msgId": "304",
          "name": null,
          "head": null,
          "msgType": "WX_EVENT_DELETE_ASSIS_SEAT",
          "msgTypeCode": null,
          "createTime": 1559801556563,
          "createId": "3",
          "status": null,
          "contextMap": {
            "CONVR_CLOSE_SEAT_NAME": "HappyZX002",
            "CONVR_CLOSE_SEAT_ID": 3,
            "CONVR_CLOSE_ASSIS_SEAT_NAME": "秀秀ZX004",
            "CONVR_CLOSE_ASSIS_SEAT_ID": 5
          },
          "msgBodyType": "EVENT",
          "code": "CLICK"
        },
        "convrOwnerEmployeeName": null,
        "fansFirstVisitDate": "2019-04-24 11:34:24",
        "assistSeatIds": "3",
        "fansComeToVisit": false,
        "seatContinueSpeakCount": 0,
        "fansLastVisitDate": "2019-06-05 22:06:38"
      },
      {
        "convrId": "1_12_ozdaP5s5Z_f-PjWk6osiGziqe1_o",
        "convrType": "XDS_WECHAT_FANS_CONVERSATION",
        "name": "Happy",
        "headImgUrl": "http://thirdwx.qlogo.cn/mmopen/EQDQDhn73NjzL3q3V9M9S9iaOqvNa5E9keuo9adAo33icmHOC8onicF7zUOa5vpwVWOXwgbW9WaBbo9ticFibxPSHKyGejzugricnh/132",
        "createId": "0",
        "createTime": "2019-05-10 22:24:29",
        "status": 1,
        "appAccountId": 12,
        "appAccountName": "销大师精选",
        "appAccountheadImgUrl": "http://wx.qlogo.cn/mmopen/v6XbW38nFOTibrbWbhCaaoH5IuXAVrLCpv3PTqnc0czmymnX5ZWiabQoVgW26iar1I6VZ2zxnF1tOpdJXXN2upZXSWQ0rrlY2nM/0",
        "convrOwnerSeatId": 40,
        "unreadNum": 0,
        "messageBody": {
          "className": "com.xkco.xkdata.commons.support.msg.body.text.TextBody",
          "msgId": "15",
          "name": null,
          "head": null,
          "msgType": "SEAT_WECHAT_KF_MSG",
          "msgTypeCode": null,
          "createTime": 1559715552007,
          "createId": "0",
          "status": null,
          "contextMap": {
            "nickName": "Happy"
          },
          "msgBodyType": "TEXT",
          "content": "被关注回复通过编辑内容，快速进行自动回复设置。开启后适用于以下场景：1）搜索公众号和扫公众号二维码关注，2）名片分享关注，3）图文页名称点击关\\n注，4）图文页右上角菜单关注，5）支付后关注。关闭后，粉丝通过以上方式关注公众号都无法收到被关注回复内容。\\n\\n"
        },
        "convrOwnerEmployeeName": null,
        "fansFirstVisitDate": "2019-05-10 22:24:28",
        "assistSeatIds": null,
        "fansComeToVisit": true,
        "seatContinueSpeakCount": 0,
        "fansLastVisitDate": "2019-06-05 14:19:11"
			},
			{
        "convrId": "1_8_oEQVk0mqiWtSQ0JOuPXguj5U2T4s",
        "convrType": "XDS_WECHAT_FANS_CONVERSATION",
        "name": "How  are  you、",
        "headImgUrl": "http://thirdwx.qlogo.cn/mmopen/eWfbQWITWhiaNvzXBR9OckVIyqFHnxBgSQ5wXNK0dRHeU5cGIHDZiaguib2NZqkG02Bj0sZsTMNicbrxkdiapWVv8ibsmKysIkKrbM/132",
        "createId": "0",
        "createTime": "2019-04-24 11:34:24",
        "status": 1,
        "appAccountId": 8,
        "appAccountName": "裂变营销实操",
        "appAccountheadImgUrl": "http://wx.qlogo.cn/mmopen/I4sDfBaAwcVBJ5icgaoALEGjpn25ZkIej1EjAy0rCtWZQ9oMsfwCWorDukubgNQOuN7j8TGzWXA9oXDFUQBYPwiczmiav4ibStxz/0",
        "convrOwnerSeatId": 40,
        "unreadNum": 0,
        "messageBody": {
          "className": "com.xkco.xkdata.commons.support.msg.body.event.EventBody",
          "msgId": "304",
          "name": null,
          "head": null,
          "msgType": "WX_EVENT_DELETE_ASSIS_SEAT",
          "msgTypeCode": null,
          "createTime": 1559801556563,
          "createId": "3",
          "status": null,
          "contextMap": {
            "CONVR_CLOSE_SEAT_NAME": "HappyZX002",
            "CONVR_CLOSE_SEAT_ID": 3,
            "CONVR_CLOSE_ASSIS_SEAT_NAME": "秀秀ZX004",
            "CONVR_CLOSE_ASSIS_SEAT_ID": 5
          },
          "msgBodyType": "EVENT",
          "code": "CLICK"
        },
        "convrOwnerEmployeeName": null,
        "fansFirstVisitDate": "2019-04-24 11:34:24",
        "assistSeatIds": "3",
        "fansComeToVisit": false,
        "seatContinueSpeakCount": 0,
        "fansLastVisitDate": "2019-06-05 22:06:38"
      },
      {
        "convrId": "1_12_ozdaP5s5Z_f-PjWk6osiGziqe1_o",
        "convrType": "XDS_WECHAT_FANS_CONVERSATION",
        "name": "Happy",
        "headImgUrl": "http://thirdwx.qlogo.cn/mmopen/EQDQDhn73NjzL3q3V9M9S9iaOqvNa5E9keuo9adAo33icmHOC8onicF7zUOa5vpwVWOXwgbW9WaBbo9ticFibxPSHKyGejzugricnh/132",
        "createId": "0",
        "createTime": "2019-05-10 22:24:29",
        "status": 1,
        "appAccountId": 12,
        "appAccountName": "销大师精选",
        "appAccountheadImgUrl": "http://wx.qlogo.cn/mmopen/v6XbW38nFOTibrbWbhCaaoH5IuXAVrLCpv3PTqnc0czmymnX5ZWiabQoVgW26iar1I6VZ2zxnF1tOpdJXXN2upZXSWQ0rrlY2nM/0",
        "convrOwnerSeatId": 40,
        "unreadNum": 0,
        "messageBody": {
          "className": "com.xkco.xkdata.commons.support.msg.body.text.TextBody",
          "msgId": "15",
          "name": null,
          "head": null,
          "msgType": "SEAT_WECHAT_KF_MSG",
          "msgTypeCode": null,
          "createTime": 1559715552007,
          "createId": "0",
          "status": null,
          "contextMap": {
            "nickName": "Happy"
          },
          "msgBodyType": "TEXT",
          "content": "被关注回复通过编辑内容，快速进行自动回复设置。开启后适用于以下场景：1）搜索公众号和扫公众号二维码关注，2）名片分享关注，3）图文页名称点击关\\n注，4）图文页右上角菜单关注，5）支付后关注。关闭后，粉丝通过以上方式关注公众号都无法收到被关注回复内容。\\n\\n"
        },
        "convrOwnerEmployeeName": null,
        "fansFirstVisitDate": "2019-05-10 22:24:28",
        "assistSeatIds": null,
        "fansComeToVisit": true,
        "seatContinueSpeakCount": 0,
        "fansLastVisitDate": "2019-06-05 14:19:11"
			},
			{
        "convrId": "1_8_oEQVk0mqiWtSQ0JOuPXguj5U2T4s",
        "convrType": "XDS_WECHAT_FANS_CONVERSATION",
        "name": "How  are  you、",
        "headImgUrl": "http://thirdwx.qlogo.cn/mmopen/eWfbQWITWhiaNvzXBR9OckVIyqFHnxBgSQ5wXNK0dRHeU5cGIHDZiaguib2NZqkG02Bj0sZsTMNicbrxkdiapWVv8ibsmKysIkKrbM/132",
        "createId": "0",
        "createTime": "2019-04-24 11:34:24",
        "status": 1,
        "appAccountId": 8,
        "appAccountName": "裂变营销实操",
        "appAccountheadImgUrl": "http://wx.qlogo.cn/mmopen/I4sDfBaAwcVBJ5icgaoALEGjpn25ZkIej1EjAy0rCtWZQ9oMsfwCWorDukubgNQOuN7j8TGzWXA9oXDFUQBYPwiczmiav4ibStxz/0",
        "convrOwnerSeatId": 40,
        "unreadNum": 0,
        "messageBody": {
          "className": "com.xkco.xkdata.commons.support.msg.body.event.EventBody",
          "msgId": "304",
          "name": null,
          "head": null,
          "msgType": "WX_EVENT_DELETE_ASSIS_SEAT",
          "msgTypeCode": null,
          "createTime": 1559801556563,
          "createId": "3",
          "status": null,
          "contextMap": {
            "CONVR_CLOSE_SEAT_NAME": "HappyZX002",
            "CONVR_CLOSE_SEAT_ID": 3,
            "CONVR_CLOSE_ASSIS_SEAT_NAME": "秀秀ZX004",
            "CONVR_CLOSE_ASSIS_SEAT_ID": 5
          },
          "msgBodyType": "EVENT",
          "code": "CLICK"
        },
        "convrOwnerEmployeeName": null,
        "fansFirstVisitDate": "2019-04-24 11:34:24",
        "assistSeatIds": "3",
        "fansComeToVisit": false,
        "seatContinueSpeakCount": 0,
        "fansLastVisitDate": "2019-06-05 22:06:38"
      },
      {
        "convrId": "1_12_ozdaP5s5Z_f-PjWk6osiGziqe1_o",
        "convrType": "XDS_WECHAT_FANS_CONVERSATION",
        "name": "Happy",
        "headImgUrl": "http://thirdwx.qlogo.cn/mmopen/EQDQDhn73NjzL3q3V9M9S9iaOqvNa5E9keuo9adAo33icmHOC8onicF7zUOa5vpwVWOXwgbW9WaBbo9ticFibxPSHKyGejzugricnh/132",
        "createId": "0",
        "createTime": "2019-05-10 22:24:29",
        "status": 1,
        "appAccountId": 12,
        "appAccountName": "销大师精选",
        "appAccountheadImgUrl": "http://wx.qlogo.cn/mmopen/v6XbW38nFOTibrbWbhCaaoH5IuXAVrLCpv3PTqnc0czmymnX5ZWiabQoVgW26iar1I6VZ2zxnF1tOpdJXXN2upZXSWQ0rrlY2nM/0",
        "convrOwnerSeatId": 40,
        "unreadNum": 0,
        "messageBody": {
          "className": "com.xkco.xkdata.commons.support.msg.body.text.TextBody",
          "msgId": "15",
          "name": null,
          "head": null,
          "msgType": "SEAT_WECHAT_KF_MSG",
          "msgTypeCode": null,
          "createTime": 1559715552007,
          "createId": "0",
          "status": null,
          "contextMap": {
            "nickName": "Happy"
          },
          "msgBodyType": "TEXT",
          "content": "被关注回复通过编辑内容，快速进行自动回复设置。开启后适用于以下场景：1）搜索公众号和扫公众号二维码关注，2）名片分享关注，3）图文页名称点击关\\n注，4）图文页右上角菜单关注，5）支付后关注。关闭后，粉丝通过以上方式关注公众号都无法收到被关注回复内容。\\n\\n"
        },
        "convrOwnerEmployeeName": null,
        "fansFirstVisitDate": "2019-05-10 22:24:28",
        "assistSeatIds": null,
        "fansComeToVisit": true,
        "seatContinueSpeakCount": 0,
        "fansLastVisitDate": "2019-06-05 14:19:11"
			},
			{
        "convrId": "1_8_oEQVk0mqiWtSQ0JOuPXguj5U2T4s",
        "convrType": "XDS_WECHAT_FANS_CONVERSATION",
        "name": "How  are  you、",
        "headImgUrl": "http://thirdwx.qlogo.cn/mmopen/eWfbQWITWhiaNvzXBR9OckVIyqFHnxBgSQ5wXNK0dRHeU5cGIHDZiaguib2NZqkG02Bj0sZsTMNicbrxkdiapWVv8ibsmKysIkKrbM/132",
        "createId": "0",
        "createTime": "2019-04-24 11:34:24",
        "status": 1,
        "appAccountId": 8,
        "appAccountName": "裂变营销实操",
        "appAccountheadImgUrl": "http://wx.qlogo.cn/mmopen/I4sDfBaAwcVBJ5icgaoALEGjpn25ZkIej1EjAy0rCtWZQ9oMsfwCWorDukubgNQOuN7j8TGzWXA9oXDFUQBYPwiczmiav4ibStxz/0",
        "convrOwnerSeatId": 40,
        "unreadNum": 0,
        "messageBody": {
          "className": "com.xkco.xkdata.commons.support.msg.body.event.EventBody",
          "msgId": "304",
          "name": null,
          "head": null,
          "msgType": "WX_EVENT_DELETE_ASSIS_SEAT",
          "msgTypeCode": null,
          "createTime": 1559801556563,
          "createId": "3",
          "status": null,
          "contextMap": {
            "CONVR_CLOSE_SEAT_NAME": "HappyZX002",
            "CONVR_CLOSE_SEAT_ID": 3,
            "CONVR_CLOSE_ASSIS_SEAT_NAME": "秀秀ZX004",
            "CONVR_CLOSE_ASSIS_SEAT_ID": 5
          },
          "msgBodyType": "EVENT",
          "code": "CLICK"
        },
        "convrOwnerEmployeeName": null,
        "fansFirstVisitDate": "2019-04-24 11:34:24",
        "assistSeatIds": "3",
        "fansComeToVisit": false,
        "seatContinueSpeakCount": 0,
        "fansLastVisitDate": "2019-06-05 22:06:38"
      },
      {
        "convrId": "1_12_ozdaP5s5Z_f-PjWk6osiGziqe1_o",
        "convrType": "XDS_WECHAT_FANS_CONVERSATION",
        "name": "Happy",
        "headImgUrl": "http://thirdwx.qlogo.cn/mmopen/EQDQDhn73NjzL3q3V9M9S9iaOqvNa5E9keuo9adAo33icmHOC8onicF7zUOa5vpwVWOXwgbW9WaBbo9ticFibxPSHKyGejzugricnh/132",
        "createId": "0",
        "createTime": "2019-05-10 22:24:29",
        "status": 1,
        "appAccountId": 12,
        "appAccountName": "销大师精选",
        "appAccountheadImgUrl": "http://wx.qlogo.cn/mmopen/v6XbW38nFOTibrbWbhCaaoH5IuXAVrLCpv3PTqnc0czmymnX5ZWiabQoVgW26iar1I6VZ2zxnF1tOpdJXXN2upZXSWQ0rrlY2nM/0",
        "convrOwnerSeatId": 40,
        "unreadNum": 0,
        "messageBody": {
          "className": "com.xkco.xkdata.commons.support.msg.body.text.TextBody",
          "msgId": "15",
          "name": null,
          "head": null,
          "msgType": "SEAT_WECHAT_KF_MSG",
          "msgTypeCode": null,
          "createTime": 1559715552007,
          "createId": "0",
          "status": null,
          "contextMap": {
            "nickName": "Happy"
          },
          "msgBodyType": "TEXT",
          "content": "被关注回复通过编辑内容，快速进行自动回复设置。开启后适用于以下场景：1）搜索公众号和扫公众号二维码关注，2）名片分享关注，3）图文页名称点击关\\n注，4）图文页右上角菜单关注，5）支付后关注。关闭后，粉丝通过以上方式关注公众号都无法收到被关注回复内容。\\n\\n"
        },
        "convrOwnerEmployeeName": null,
        "fansFirstVisitDate": "2019-05-10 22:24:28",
        "assistSeatIds": null,
        "fansComeToVisit": true,
        "seatContinueSpeakCount": 0,
        "fansLastVisitDate": "2019-06-05 14:19:11"
      }
]

export default itemData